/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { animated } from "@react-spring/three";

export function M({ x, rotation, ...props }) {
  const { nodes, materials } = useGLTF("glb/tilem.glb");
  return (
    <animated.group
      {...props}
      dispose={null}
      rotation-z={rotation}
      position-x={x}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.27, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.001"]}
        position={[0.701, -0.374, 0.585]}
        rotation={[0, 0, -3.134]}
        scale={1.753}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.002"]}
        position={[-0.78, 0.366, 0.55]}
        scale={1.531}
      />
    </animated.group>
  );
}

useGLTF.preload("glb/tilem.glb");
