/*
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { animated, SpringValue } from "@react-spring/three";

interface Props {
  offsetX: number;
  rotation: SpringValue<number>;
}

export function Model({ offsetX, rotation, ...props }: Props) {
  const { nodes, materials } = useGLTF("glb/Scrabble/tile3.glb");
  return (
    <animated.group
      {...props}
      dispose={null}
      rotation-z={rotation}
      position-x={offsetX}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, -0.27, -1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.001"]}
        position={[0.518, -0.374, 0.627]}
        rotation={[0, 0, -3.134]}
        scale={1.853}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.002"]}
        position={[-0.547, 0.368, 0.514]}
        scale={1.631}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials["Material.001"]}
        position={[0.69, 0.359, 0.773]}
        scale={0.333}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials["Material.003"]}
        position={[-0.677, -0.366, 0.797]}
        rotation={[0.015, 0.015, 3.131]}
        scale={0.333}
      />
    </animated.group>
  );
}

useGLTF.preload("/tile3.glb");
